# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessArena.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChessArena.proto',
  package='GameManager',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x43hessArena.proto\x12\x0bGameManager\"8\n\x0fGameInformation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x05\x63hess\x18\x02 \x01(\tH\x00\x42\x06\n\x04game\"\\\n\x14GameStartInformation\x12\r\n\x05start\x18\x01 \x01(\x08\x12&\n\tchessMove\x18\x02 \x01(\x0b\x32\x11.GameManager.MoveH\x00\x42\r\n\x0bopponentAct\"L\n\x04Move\x12\'\n\x05\x63hess\x18\x01 \x01(\x0b\x32\x16.GameManager.ChessMoveH\x00\x12\x13\n\x0b\x64iagnostics\x18\x02 \x01(\tB\x06\n\x04game\"\x88\x02\n\tChessMove\x12\x16\n\x0estart_position\x18\x01 \x01(\t\x12\x14\n\x0c\x65nd_position\x18\x02 \x01(\t\x12\r\n\x05\x63heck\x18\x03 \x01(\x08\x12\x12\n\ncheck_mate\x18\x04 \x01(\x08\x12\x10\n\x08\x63\x61stling\x18\x05 \x01(\x08\x12\x43\n\x10promotion_result\x18\x06 \x01(\x0e\x32).GameManager.ChessMove.PromotionPieceType\"S\n\x12PromotionPieceType\x12\x10\n\x0cNO_PROMOTION\x10\x00\x12\t\n\x05QUEEN\x10\x01\x12\x08\n\x04ROOK\x10\x02\x12\n\n\x06KNIGHT\x10\x03\x12\n\n\x06\x42ISHOP\x10\x04\x32\x91\x01\n\x0bGameService\x12O\n\nInitialize\x12\x1c.GameManager.GameInformation\x1a!.GameManager.GameStartInformation\"\x00\x12\x31\n\x03\x41\x63t\x12\x11.GameManager.Move\x1a\x11.GameManager.Move\"\x00(\x01\x30\x01\x62\x06proto3'
)



_CHESSMOVE_PROMOTIONPIECETYPE = _descriptor.EnumDescriptor(
  name='PromotionPieceType',
  full_name='GameManager.ChessMove.PromotionPieceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_PROMOTION', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='QUEEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROOK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KNIGHT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BISHOP', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=445,
  serialized_end=528,
)
_sym_db.RegisterEnumDescriptor(_CHESSMOVE_PROMOTIONPIECETYPE)


_GAMEINFORMATION = _descriptor.Descriptor(
  name='GameInformation',
  full_name='GameManager.GameInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GameManager.GameInformation.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chess', full_name='GameManager.GameInformation.chess', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='game', full_name='GameManager.GameInformation.game',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=33,
  serialized_end=89,
)


_GAMESTARTINFORMATION = _descriptor.Descriptor(
  name='GameStartInformation',
  full_name='GameManager.GameStartInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='GameManager.GameStartInformation.start', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chessMove', full_name='GameManager.GameStartInformation.chessMove', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='opponentAct', full_name='GameManager.GameStartInformation.opponentAct',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=91,
  serialized_end=183,
)


_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='GameManager.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chess', full_name='GameManager.Move.chess', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='diagnostics', full_name='GameManager.Move.diagnostics', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='game', full_name='GameManager.Move.game',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=185,
  serialized_end=261,
)


_CHESSMOVE = _descriptor.Descriptor(
  name='ChessMove',
  full_name='GameManager.ChessMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_position', full_name='GameManager.ChessMove.start_position', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_position', full_name='GameManager.ChessMove.end_position', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='check', full_name='GameManager.ChessMove.check', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='check_mate', full_name='GameManager.ChessMove.check_mate', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='castling', full_name='GameManager.ChessMove.castling', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='promotion_result', full_name='GameManager.ChessMove.promotion_result', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHESSMOVE_PROMOTIONPIECETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=528,
)

_GAMEINFORMATION.oneofs_by_name['game'].fields.append(
  _GAMEINFORMATION.fields_by_name['chess'])
_GAMEINFORMATION.fields_by_name['chess'].containing_oneof = _GAMEINFORMATION.oneofs_by_name['game']
_GAMESTARTINFORMATION.fields_by_name['chessMove'].message_type = _MOVE
_GAMESTARTINFORMATION.oneofs_by_name['opponentAct'].fields.append(
  _GAMESTARTINFORMATION.fields_by_name['chessMove'])
_GAMESTARTINFORMATION.fields_by_name['chessMove'].containing_oneof = _GAMESTARTINFORMATION.oneofs_by_name['opponentAct']
_MOVE.fields_by_name['chess'].message_type = _CHESSMOVE
_MOVE.oneofs_by_name['game'].fields.append(
  _MOVE.fields_by_name['chess'])
_MOVE.fields_by_name['chess'].containing_oneof = _MOVE.oneofs_by_name['game']
_CHESSMOVE.fields_by_name['promotion_result'].enum_type = _CHESSMOVE_PROMOTIONPIECETYPE
_CHESSMOVE_PROMOTIONPIECETYPE.containing_type = _CHESSMOVE
DESCRIPTOR.message_types_by_name['GameInformation'] = _GAMEINFORMATION
DESCRIPTOR.message_types_by_name['GameStartInformation'] = _GAMESTARTINFORMATION
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.message_types_by_name['ChessMove'] = _CHESSMOVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameInformation = _reflection.GeneratedProtocolMessageType('GameInformation', (_message.Message,), {
  'DESCRIPTOR' : _GAMEINFORMATION,
  '__module__' : 'ChessArena_pb2'
  # @@protoc_insertion_point(class_scope:GameManager.GameInformation)
  })
_sym_db.RegisterMessage(GameInformation)

GameStartInformation = _reflection.GeneratedProtocolMessageType('GameStartInformation', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTARTINFORMATION,
  '__module__' : 'ChessArena_pb2'
  # @@protoc_insertion_point(class_scope:GameManager.GameStartInformation)
  })
_sym_db.RegisterMessage(GameStartInformation)

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), {
  'DESCRIPTOR' : _MOVE,
  '__module__' : 'ChessArena_pb2'
  # @@protoc_insertion_point(class_scope:GameManager.Move)
  })
_sym_db.RegisterMessage(Move)

ChessMove = _reflection.GeneratedProtocolMessageType('ChessMove', (_message.Message,), {
  'DESCRIPTOR' : _CHESSMOVE,
  '__module__' : 'ChessArena_pb2'
  # @@protoc_insertion_point(class_scope:GameManager.ChessMove)
  })
_sym_db.RegisterMessage(ChessMove)



_GAMESERVICE = _descriptor.ServiceDescriptor(
  name='GameService',
  full_name='GameManager.GameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=531,
  serialized_end=676,
  methods=[
  _descriptor.MethodDescriptor(
    name='Initialize',
    full_name='GameManager.GameService.Initialize',
    index=0,
    containing_service=None,
    input_type=_GAMEINFORMATION,
    output_type=_GAMESTARTINFORMATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Act',
    full_name='GameManager.GameService.Act',
    index=1,
    containing_service=None,
    input_type=_MOVE,
    output_type=_MOVE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESERVICE)

DESCRIPTOR.services_by_name['GameService'] = _GAMESERVICE

# @@protoc_insertion_point(module_scope)
